### ISSUE TITLE
Chome doesn't show the video poster/cover after recording

### ISSUE THREAD

**Issue by bago2k4** [betajs/betajs-media-components#40]
On Chrome 67.0.3396.99 (Mac OSX 10.13.6) after recording a video with your recorder i see a black box instead of the cover.

I believe that Chrome has problems showing the image from the blob created in javascript.
That or it doesn't like showing images inside the video tag, i tried setting it as the poster property but it doesn't work too.

**Comment by Bane-D** [comment]
Hi,

We have made some updates and I believe it should work properly for you now. Can you please test it out and let us know how it goes?

To test it out, you would need to updated betajs-media (not betajs-media-components) at which time it should work fine.

Regards,
Bane

**Comment by bago2k4** [comment]
Sorry for the delay, that worked very well. Thanks for your fix.
